'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./component/SessionWrapper";
import LayoutWrapper from "./components/LayoutWrapper";
import { ThemeProvider } from "./context/ThemeContext";
import { Provider } from 'react-redux';
import { SessionProvider } from 'next-auth/react'; // Add this import
import { store } from './Store/store';
import LoadingOverlay from './components/LoadingOverlay';
import SessionMonitor from './components/SessionMonitor';
// import OfflineIndicator from './components/OfflineIndicator';
import Notification from './components/Notification';
import FloatingButton from './components/FloatingButton';
import AudioPlayer from './components/AudioPlayer'; // Add this import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider store={store}>
          <SessionWrapper>
            <ThemeProvider>
              <AudioPlayer /> {/* Add this component */}
              <LoadingOverlay />
              <SessionMonitor />
              {/* <OfflineIndicator /> */}
              <Notification />
              {/* Removed duplicate ThemeProvider and ReduxProvider */}
              {/* SessionProvider should be inside SessionWrapper or SessionWrapper should provide the session context */}
              <LayoutWrapper>
                {children}
                <FloatingButton />
              </LayoutWrapper>
            </ThemeProvider>
          </SessionWrapper>
        </Provider>
      </body>
    </html>
  );
}

// export const metadata = {
//   title: "Leveling System",
//   description: "Generated by create next app",
// };